name: TestCICD

on:
  push:
    branches: 
      - lab-7
  pull_request:
    branches: 
      - lab-7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze lib/templates/lab7/main.dart

      - name: Run tests
        run: flutter test test/test_main.dart

      - name: Build web
        run: flutter build web --release --target=lib/templates/lab7/main.dart

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

  build_win:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze lib/templates/lab7/main.dart

      - name: Run tests
        run: flutter test test/test_main.dart

      - name: Build Windows
        run: flutter build windows --release --target=lib/templates/lab7/main.dart