name: TestCICD

on:
  push:
    branches: 
      - lab-7
  pull_request:
    branches: 
      - lab-7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Install dependencies
        run: flutter pub get

      - run: flutter analyze lib/templates/lab7/main.dart
      - run: flutter test test/test_main.dart
      - run: flutter build web --release lib/templates/lab7/main.dart
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /Sum24FlutterCourse/
          customArgs: "lib/templates/lab7/main.dart"

  build_win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Install dependencies
        run: flutter pub get

      - run: flutter analyze lib/templates/lab7/main.dart
      - run: flutter test test/test_main.dart
      - run: flutter build windows --release lib/templates/lab7/main.dart